name: u3_peliculas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  card_swiper: ^2.0.4 # Aqui agregamos el Card_swiper de internet
  http: ^0.13.5 # Espara consumir servicions web
  provider: ^6.0.5 # Manejador de estado   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
